<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $foods = [
            // Makanan Pokok
            [
                'name' => 'Nasi Putih',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 130.0,
                'protein_per_100g' => 2.7,
                'carbohydrates_per_100g' => 28.2,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 0.4,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Nasi Goreng',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 168.0,
                'protein_per_100g' => 5.2,
                'carbohydrates_per_100g' => 24.1,
                'fat_per_100g' => 6.2,
                'fiber_per_100g' => 1.1,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Nasi Kuning',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 150.0,
                'protein_per_100g' => 3.1,
                'carbohydrates_per_100g' => 26.5,
                'fat_per_100g' => 3.8,
                'fiber_per_100g' => 0.5,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Mie Goreng',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 180.0,
                'protein_per_100g' => 4.5,
                'carbohydrates_per_100g' => 26.0,
                'fat_per_100g' => 7.0,
                'fiber_per_100g' => 1.5,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Lauk Pauk (Ayam & Daging)
            [
                'name' => 'Ayam Bakar',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 195.0,
                'protein_per_100g' => 25.0,
                'carbohydrates_per_100g' => 3.5,
                'fat_per_100g' => 8.8,
                'fiber_per_100g' => 0.2,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Ayam Goreng',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 246.0,
                'protein_per_100g' => 22.0,
                'carbohydrates_per_100g' => 4.0,
                'fat_per_100g' => 15.5,
                'fiber_per_100g' => 0.1,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Rendang Daging Sapi',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 268.0,
                'protein_per_100g' => 24.5,
                'carbohydrates_per_100g' => 6.2,
                'fat_per_100g' => 16.8,
                'fiber_per_100g' => 0.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Sate Ayam',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 218.0,
                'protein_per_100g' => 20.0,
                'carbohydrates_per_100g' => 7.8,
                'fat_per_100g' => 12.0,
                'fiber_per_100g' => 0.6,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Ikan Bakar',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 142.0,
                'protein_per_100g' => 22.5,
                'carbohydrates_per_100g' => 1.8,
                'fat_per_100g' => 5.2,
                'fiber_per_100g' => 0.0,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Telur, Tahu & Tempe
            [
                'name' => 'Telur Rebus',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 155.0,
                'protein_per_100g' => 12.6,
                'carbohydrates_per_100g' => 1.1,
                'fat_per_100g' => 10.6,
                'fiber_per_100g' => 0.0,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Telur Dadar',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 196.0,
                'protein_per_100g' => 11.8,
                'carbohydrates_per_100g' => 2.4,
                'fat_per_100g' => 15.3,
                'fiber_per_100g' => 0.0,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Tempe Goreng',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 225.0,
                'protein_per_100g' => 14.0,
                'carbohydrates_per_100g' => 13.5,
                'fat_per_100g' => 14.2,
                'fiber_per_100g' => 2.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Tahu Goreng',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 115.0,
                'protein_per_100g' => 9.7,
                'carbohydrates_per_100g' => 4.2,
                'fat_per_100g' => 7.1,
                'fiber_per_100g' => 1.2,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Sayuran
            [
                'name' => 'Sayur Bayam Bening',
                'category' => 'Sayuran',
                'calories_per_100g' => 23.0,
                'protein_per_100g' => 2.2,
                'carbohydrates_per_100g' => 3.6,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 1.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Sayur Sop Ayam Sayuran',
                'category' => 'Sayuran',
                'calories_per_100g' => 45.0,
                'protein_per_100g' => 3.5,
                'carbohydrates_per_100g' => 4.8,
                'fat_per_100g' => 1.5,
                'fiber_per_100g' => 1.4,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Gado-Gado',
                'category' => 'Sayuran',
                'calories_per_100g' => 132.0,
                'protein_per_100g' => 5.8,
                'carbohydrates_per_100g' => 11.2,
                'fat_per_100g' => 7.8,
                'fiber_per_100g' => 2.6,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Capcay Sayur',
                'category' => 'Sayuran',
                'calories_per_100g' => 52.0,
                'protein_per_100g' => 2.8,
                'carbohydrates_per_100g' => 6.4,
                'fat_per_100g' => 2.0,
                'fiber_per_100g' => 2.1,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Buah-buahan
            [
                'name' => 'Pisang',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 89.0,
                'protein_per_100g' => 1.1,
                'carbohydrates_per_100g' => 22.8,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 2.6,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Apel',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 52.0,
                'protein_per_100g' => 0.3,
                'carbohydrates_per_100g' => 13.8,
                'fat_per_100g' => 0.2,
                'fiber_per_100g' => 2.4,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Pepaya',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 39.0,
                'protein_per_100g' => 0.5,
                'carbohydrates_per_100g' => 9.8,
                'fat_per_100g' => 0.1,
                'fiber_per_100g' => 1.7,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Alpukat',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 160.0,
                'protein_per_100g' => 2.0,
                'carbohydrates_per_100g' => 8.5,
                'fat_per_100g' => 14.7,
                'fiber_per_100g' => 6.7,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            // Makanan Modern, Western & Cepat Saji
            [
                'name' => 'Burger Daging Sapi',
                'category' => 'Makanan Cepat Saji',
                'calories_per_100g' => 260.0,
                'protein_per_100g' => 13.5,
                'carbohydrates_per_100g' => 28.0,
                'fat_per_100g' => 11.2,
                'fiber_per_100g' => 1.8,
                'nutrition_source' => 'USDA & Komposisi Pangan Olahan',
            ],
            [
                'name' => 'Cheeseburger',
                'category' => 'Makanan Cepat Saji',
                'calories_per_100g' => 303.0,
                'protein_per_100g' => 15.8,
                'carbohydrates_per_100g' => 26.5,
                'fat_per_100g' => 15.2,
                'fiber_per_100g' => 1.5,
                'nutrition_source' => 'USDA FoodData Central',
            ],
            [
                'name' => 'Pizza Daging & Keju',
                'category' => 'Makanan Cepat Saji',
                'calories_per_100g' => 266.0,
                'protein_per_100g' => 11.4,
                'carbohydrates_per_100g' => 33.3,
                'fat_per_100g' => 9.8,
                'fiber_per_100g' => 2.3,
                'nutrition_source' => 'USDA FoodData Central',
            ],
            [
                'name' => 'Kentang Goreng (French Fries)',
                'category' => 'Makanan Cepat Saji',
                'calories_per_100g' => 312.0,
                'protein_per_100g' => 3.4,
                'carbohydrates_per_100g' => 41.4,
                'fat_per_100g' => 15.0,
                'fiber_per_100g' => 3.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Sandwich Daging & Telur',
                'category' => 'Makanan Ringan',
                'calories_per_100g' => 215.0,
                'protein_per_100g' => 10.5,
                'carbohydrates_per_100g' => 24.2,
                'fat_per_100g' => 8.6,
                'fiber_per_100g' => 1.9,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 155.0,
                'protein_per_100g' => 7.8,
                'carbohydrates_per_100g' => 21.0,
                'fat_per_100g' => 4.6,
                'fiber_per_100g' => 1.7,
                'nutrition_source' => 'USDA & TKPI Kemenkes RI',
            ],
            [
                'name' => 'Salad Sayur Segar',
                'category' => 'Sayuran',
                'calories_per_100g' => 65.0,
                'protein_per_100g' => 2.5,
                'carbohydrates_per_100g' => 6.2,
                'fat_per_100g' => 3.5,
                'fiber_per_100g' => 2.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Bakso Sapi Kuah',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 125.0,
                'protein_per_100g' => 10.2,
                'carbohydrates_per_100g' => 12.0,
                'fat_per_100g' => 3.8,
                'fiber_per_100g' => 0.5,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Soto Ayam Kuah Bening',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 95.0,
                'protein_per_100g' => 8.5,
                'carbohydrates_per_100g' => 6.5,
                'fat_per_100g' => 3.2,
                'fiber_per_100g' => 0.6,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Ayam Geprek Sambal',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 265.0,
                'protein_per_100g' => 21.0,
                'carbohydrates_per_100g' => 9.5,
                'fat_per_100g' => 16.0,
                'fiber_per_100g' => 0.8,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Roti Bakar Coklat Keju',
                'category' => 'Makanan Ringan',
                'calories_per_100g' => 295.0,
                'protein_per_100g' => 7.5,
                'carbohydrates_per_100g' => 45.0,
                'fat_per_100g' => 9.8,
                'fiber_per_100g' => 2.1,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Martabak Telur',
                'category' => 'Makanan Ringan',
                'calories_per_100g' => 240.0,
                'protein_per_100g' => 10.5,
                'carbohydrates_per_100g' => 18.0,
                'fat_per_100g' => 14.5,
                'fiber_per_100g' => 1.2,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Siomay Ikan Bandung',
                'category' => 'Makanan Ringan',
                'calories_per_100g' => 165.0,
                'protein_per_100g' => 8.8,
                'carbohydrates_per_100g' => 18.5,
                'fat_per_100g' => 6.2,
                'fiber_per_100g' => 1.1,
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
        ];

        foreach ($foods as $food) {
            Food::updateOrCreate(
                ['name' => $food['name']],
                $food
            );
        }
    }
}
