<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $foods = [
            // Makanan Pokok
            [
                'name' => 'Nasi Putih',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 130.0,
                'protein_per_100g' => 2.7,
                'carbohydrates_per_100g' => 28.2,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 0.4,
                'sugar_g' => 0.1,
                'sodium_mg' => 1.0,
                'serving_size' => '1 porsi mangkuk sedang (150g)',
                'health_grade' => 'B',
                'icon_emoji' => '🍚',
                'description' => 'Beras putih pulen matang kukus, sumber karbohidrat utama masyarakat Indonesia.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Nasi Goreng Spesial',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 168.0,
                'protein_per_100g' => 5.2,
                'carbohydrates_per_100g' => 24.1,
                'fat_per_100g' => 6.2,
                'fiber_per_100g' => 1.1,
                'sugar_g' => 1.8,
                'sodium_mg' => 420.0,
                'serving_size' => '1 piring porsi (200g)',
                'health_grade' => 'C',
                'icon_emoji' => '🍳',
                'description' => 'Nasi goreng harum bumbu rempah dengan telur, suwiran ayam, dan kecap manis.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Nasi Kuning Komplit',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 150.0,
                'protein_per_100g' => 3.1,
                'carbohydrates_per_100g' => 26.5,
                'fat_per_100g' => 3.8,
                'fiber_per_100g' => 0.5,
                'sugar_g' => 0.5,
                'sodium_mg' => 180.0,
                'serving_size' => '1 porsi (180g)',
                'health_grade' => 'B',
                'icon_emoji' => '🍛',
                'description' => 'Nasi gurih dimasak dengan santan alami dan kunyit aromatik berkhasiat antioksidan.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Mie Goreng Spesial',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 180.0,
                'protein_per_100g' => 4.5,
                'carbohydrates_per_100g' => 26.0,
                'fat_per_100g' => 7.0,
                'fiber_per_100g' => 1.5,
                'sugar_g' => 2.5,
                'sodium_mg' => 580.0,
                'serving_size' => '1 porsi piring (180g)',
                'health_grade' => 'C',
                'icon_emoji' => '🍜',
                'description' => 'Mie telur dimasak dengan sayuran kol, sawi, dan bumbu kecap gurih.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 155.0,
                'protein_per_100g' => 7.8,
                'carbohydrates_per_100g' => 21.0,
                'fat_per_100g' => 4.6,
                'fiber_per_100g' => 1.7,
                'sugar_g' => 3.2,
                'sodium_mg' => 340.0,
                'serving_size' => '1 piring sedang (220g)',
                'health_grade' => 'B',
                'icon_emoji' => '🍝',
                'description' => 'Pasta gandum durum dengan saus tomat daging cincang kaya likopen dan protein.',
                'nutrition_source' => 'USDA & TKPI Kemenkes RI',
            ],

            // Lauk Pauk (Protein Tinggi)
            [
                'name' => 'Dada Ayam Bakar',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 195.0,
                'protein_per_100g' => 25.0,
                'carbohydrates_per_100g' => 3.5,
                'fat_per_100g' => 8.8,
                'fiber_per_100g' => 0.2,
                'sugar_g' => 2.0,
                'sodium_mg' => 220.0,
                'serving_size' => '1 potong dada sedang (120g)',
                'health_grade' => 'A',
                'icon_emoji' => '🍗',
                'description' => 'Dada ayam tanpa kulit dibumbui rempah ketumbar dan dibakar tanpa minyak berlebih.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Ayam Goreng Lengkuas',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 246.0,
                'protein_per_100g' => 22.0,
                'carbohydrates_per_100g' => 4.0,
                'fat_per_100g' => 15.5,
                'fiber_per_100g' => 0.1,
                'sugar_g' => 0.5,
                'sodium_mg' => 310.0,
                'serving_size' => '1 potong paha/dada (100g)',
                'health_grade' => 'B',
                'icon_emoji' => '🍗',
                'description' => 'Ayam ungkep bumbu kuning tradisional dengan kremesan serundeng lengkuas.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Rendang Daging Sapi',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 268.0,
                'protein_per_100g' => 24.5,
                'carbohydrates_per_100g' => 6.2,
                'fat_per_100g' => 16.8,
                'fiber_per_100g' => 0.8,
                'sugar_g' => 1.5,
                'sodium_mg' => 380.0,
                'serving_size' => '1 potong sedang (70g)',
                'health_grade' => 'B',
                'icon_emoji' => '🥩',
                'description' => 'Daging sapi has dalam dimasak perlahan dengan santan dan rempah khas Minangkabau.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Ikan Gurame Bakar Madu',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 142.0,
                'protein_per_100g' => 22.5,
                'carbohydrates_per_100g' => 1.8,
                'fat_per_100g' => 5.2,
                'fiber_per_100g' => 0.0,
                'sugar_g' => 1.2,
                'sodium_mg' => 150.0,
                'serving_size' => '1 ekor sedang (150g fillet)',
                'health_grade' => 'A',
                'icon_emoji' => '🐟',
                'description' => 'Ikan air tawar kaya omega-3 dan protein berkualitas tinggi rendah lemak jenuh.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Telur Ayam Rebus',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 155.0,
                'protein_per_100g' => 12.6,
                'carbohydrates_per_100g' => 1.1,
                'fat_per_100g' => 10.6,
                'fiber_per_100g' => 0.0,
                'sugar_g' => 0.6,
                'sodium_mg' => 124.0,
                'serving_size' => '1 butir telur utuh (55g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥚',
                'description' => 'Sumber protein biologis sempurna lengkap dengan kolin untuk fungsi kognitif otak.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Telur Dadar Daun Bawang',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 196.0,
                'protein_per_100g' => 11.8,
                'carbohydrates_per_100g' => 2.4,
                'fat_per_100g' => 15.3,
                'fiber_per_100g' => 0.0,
                'sugar_g' => 0.8,
                'sodium_mg' => 240.0,
                'serving_size' => '1 lembar dadar (60g)',
                'health_grade' => 'B',
                'icon_emoji' => '🍳',
                'description' => 'Telur kocok dengan irisan daun bawang segar, digoreng renyah keemasan.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Tempe Goreng Gurih',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 225.0,
                'protein_per_100g' => 14.0,
                'carbohydrates_per_100g' => 13.5,
                'fat_per_100g' => 14.2,
                'fiber_per_100g' => 2.8,
                'sugar_g' => 0.7,
                'sodium_mg' => 180.0,
                'serving_size' => '2 potong tempe (80g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥢',
                'description' => 'Superfood fermentasi kedelai asli Nusantara kaya probiotik, serat, dan isoflavon.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Tahu Sutra Kukus / Rebus',
                'category' => 'Lauk Pauk',
                'calories_per_100g' => 80.0,
                'protein_per_100g' => 8.5,
                'carbohydrates_per_100g' => 2.1,
                'fat_per_100g' => 4.2,
                'fiber_per_100g' => 1.0,
                'sugar_g' => 0.3,
                'sodium_mg' => 30.0,
                'serving_size' => '1 potong besar (100g)',
                'health_grade' => 'A',
                'icon_emoji' => '🤍',
                'description' => 'Olahan kedelai rendah kalori yang sangat ramah pencernaan dan tinggi kalsium.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Sayuran (Kaya Serat & Mikronutrien)
            [
                'name' => 'Sayur Bayam Bening Jagung',
                'category' => 'Sayuran',
                'calories_per_100g' => 23.0,
                'protein_per_100g' => 2.2,
                'carbohydrates_per_100g' => 3.6,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 1.8,
                'sugar_g' => 0.9,
                'sodium_mg' => 45.0,
                'serving_size' => '1 mangkuk kuah (150g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥬',
                'description' => 'Sayur daun bayam hijau segar dengan potongan jagung manis dan temu kunci penambah selera.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Sayur Sop Ayam Brokoli',
                'category' => 'Sayuran',
                'calories_per_100g' => 45.0,
                'protein_per_100g' => 3.5,
                'carbohydrates_per_100g' => 4.8,
                'fat_per_100g' => 1.5,
                'fiber_per_100g' => 1.4,
                'sugar_g' => 1.2,
                'sodium_mg' => 120.0,
                'serving_size' => '1 mangkuk sop (200g)',
                'health_grade' => 'A',
                'icon_emoji' => '🍲',
                'description' => 'Sop bening hangat berisi wortel, brokoli, buncis, kentang, dan suwiran kaldu ayam.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Gado-Gado Siram Kacang',
                'category' => 'Sayuran',
                'calories_per_100g' => 132.0,
                'protein_per_100g' => 5.8,
                'carbohydrates_per_100g' => 11.2,
                'fat_per_100g' => 7.8,
                'fiber_per_100g' => 2.6,
                'sugar_g' => 3.5,
                'sodium_mg' => 280.0,
                'serving_size' => '1 piring saji (250g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥗',
                'description' => 'Salad khas Indonesia dengan rebusan kacang panjang, tauge, kentang, tahu, telur, dan saus kacang.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Capcay Sayuran Lengkap',
                'category' => 'Sayuran',
                'calories_per_100g' => 52.0,
                'protein_per_100g' => 2.8,
                'carbohydrates_per_100g' => 6.4,
                'fat_per_100g' => 2.0,
                'fiber_per_100g' => 2.1,
                'sugar_g' => 1.6,
                'sodium_mg' => 160.0,
                'serving_size' => '1 porsi mangkuk (180g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥦',
                'description' => 'Tumisan aneka sayur kembang kol, sawi, wortel, dan jamur dengan saus tiram gurih.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Buah-buahan Segar
            [
                'name' => 'Pisang Cavendish / Ambon',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 89.0,
                'protein_per_100g' => 1.1,
                'carbohydrates_per_100g' => 22.8,
                'fat_per_100g' => 0.3,
                'fiber_per_100g' => 2.6,
                'sugar_g' => 12.2,
                'sodium_mg' => 1.0,
                'serving_size' => '1 buah pisang ukuran sedang (118g)',
                'health_grade' => 'A',
                'icon_emoji' => '🍌',
                'description' => 'Buah berenergi tinggi kaya kalium yang sangat bagus dikonsumsi sebelum atau setelah olahraga.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Apel Fuji Segar',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 52.0,
                'protein_per_100g' => 0.3,
                'carbohydrates_per_100g' => 13.8,
                'fat_per_100g' => 0.2,
                'fiber_per_100g' => 2.4,
                'sugar_g' => 10.4,
                'sodium_mg' => 1.0,
                'serving_size' => '1 buah apel sedang (150g)',
                'health_grade' => 'A',
                'icon_emoji' => '🍎',
                'description' => 'Apel renyah manis kaya antioksidan flavonoid dan serat larut pektin untuk pencernaan sehat.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
            [
                'name' => 'Alpukat Mentega',
                'category' => 'Buah-buahan',
                'calories_per_100g' => 160.0,
                'protein_per_100g' => 2.0,
                'carbohydrates_per_100g' => 8.5,
                'fat_per_100g' => 14.7,
                'fiber_per_100g' => 6.7,
                'sugar_g' => 0.7,
                'sodium_mg' => 7.0,
                'serving_size' => 'Setengah buah alpukat (100g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥑',
                'description' => 'Superfood sumber lemak tak jenuh tunggal yang melindungi kesehatan kardiovaskular dan jantung.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],

            // Minuman & Camilan Sehat
            [
                'name' => 'Susu Kedelai Murni Tanpa Gula',
                'category' => 'Minuman Sehat',
                'calories_per_100g' => 45.0,
                'protein_per_100g' => 3.6,
                'carbohydrates_per_100g' => 2.8,
                'fat_per_100g' => 2.0,
                'fiber_per_100g' => 0.5,
                'sugar_g' => 1.0,
                'sodium_mg' => 35.0,
                'serving_size' => '1 gelas (240ml)',
                'health_grade' => 'A',
                'icon_emoji' => '🥛',
                'description' => 'Minuman nabati tinggi protein bebas laktosa dan kolesterol.',
                'nutrition_source' => 'USDA & Komposisi Pangan',
            ],
            [
                'name' => 'Teh Hijau Seduh Alami',
                'category' => 'Minuman Sehat',
                'calories_per_100g' => 2.0,
                'protein_per_100g' => 0.2,
                'carbohydrates_per_100g' => 0.3,
                'fat_per_100g' => 0.0,
                'fiber_per_100g' => 0.0,
                'sugar_g' => 0.0,
                'sodium_mg' => 2.0,
                'serving_size' => '1 cangkir (200ml)',
                'health_grade' => 'A',
                'icon_emoji' => '🍵',
                'description' => 'Minuman tanpa kalori kaya epigallocatechin gallate (EGCG) untuk metabolisme optimal.',
                'nutrition_source' => 'USDA FoodData Central',
            ],
            [
                'name' => 'Yogurt Yunani (Greek Yogurt) Plain',
                'category' => 'Camilan Sehat',
                'calories_per_100g' => 59.0,
                'protein_per_100g' => 10.0,
                'carbohydrates_per_100g' => 3.6,
                'fat_per_100g' => 0.4,
                'fiber_per_100g' => 0.0,
                'sugar_g' => 3.2,
                'sodium_mg' => 36.0,
                'serving_size' => '1 cup kecil (150g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥣',
                'description' => 'Yogurt kental tinggi protein alami dengan kultur bakteri aktif ramah usus.',
                'nutrition_source' => 'USDA FoodData Central',
            ],
            [
                'name' => 'Oatmeal Gandum Utuh',
                'category' => 'Makanan Pokok',
                'calories_per_100g' => 68.0,
                'protein_per_100g' => 2.5,
                'carbohydrates_per_100g' => 12.0,
                'fat_per_100g' => 1.4,
                'fiber_per_100g' => 1.7,
                'sugar_g' => 0.3,
                'sodium_mg' => 5.0,
                'serving_size' => '1 mangkuk bubur oat (180g)',
                'health_grade' => 'A',
                'icon_emoji' => '🥣',
                'description' => 'Gandum utuh kaya serat beta-glukan terbukti menurunkan kadar kolesterol jahat LDL.',
                'nutrition_source' => 'Tabel Komposisi Pangan Indonesia (TKPI) Kemenkes RI',
            ],
        ];

        foreach ($foods as $food) {
            Food::updateOrCreate(
                ['name' => $food['name']],
                $food
            );
        }
    }
}
